### ISSUE TITLE
环境

### ISSUE THREAD

**Issue by mirage0** [StevenWD/DRGD#1]
您好~我想请问一下关于tensorflow的版本问题，在代码中使用到了tf的batch_gather()函数，这个函数似乎只有1.13版本存在,所以我想请教一下您的环境，期待您的回复。

**Comment by StevenWD** [comment]
Python 3.6.5 + Tensorflow 1.12

**Comment by mirage0** [comment]
谢谢您的回复，最近在学习这方面的知识，不知道方不方便留个联系方式，有些问题想要请教您。

**Comment by StevenWD** [comment]
Sorry for getting back to you so late. You can send email to me yyj_stevenwd@163.com if you have any question.
